CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    authorities VARCHAR2(1000)
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    document VARCHAR2(100),
    phone VARCHAR2(100),
    email VARCHAR2(255),
    address VARCHAR2(255),
    birth_date DATE,
    observations VARCHAR2(1000),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate VARCHAR2(20),
    brand VARCHAR2(100),
    model VARCHAR2(100),
    manufacture_date DATE,
    color VARCHAR2(50),
    observations VARCHAR2(1000),
    kilometers NUMBER(10,2),
    vehicle_id VARCHAR2(100),
    client_id NUMBER,
    CONSTRAINT fk_vehicles_client FOREIGN KEY (client_id) REFERENCES clients(id)
);
