CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    authorities VARCHAR2(1000)
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    document VARCHAR2(100),
    phone VARCHAR2(100),
    email VARCHAR2(255),
    address VARCHAR2(255),
    birth_date DATE,
    observations VARCHAR2(1000),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate VARCHAR2(20),
    brand VARCHAR2(100),
    model VARCHAR2(100),
    manufacture_date DATE,
    color VARCHAR2(50),
    observations VARCHAR2(1000),
    kilometers NUMBER(10,2),
    chassis_id VARCHAR2(100),
    client_id NUMBER,
    CONSTRAINT fk_vehicles_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Tabela de Ordens de Serviço
CREATE TABLE service_orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(50) NOT NULL UNIQUE,
    vehicle_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    description CLOB,
    problem_description CLOB,
    diagnosis CLOB,
    solution_description CLOB,
    status VARCHAR2(20) NOT NULL DEFAULT 'PENDING',
    labor_cost NUMBER(10,2) DEFAULT 0,
    parts_cost NUMBER(10,2) DEFAULT 0,
    total_cost NUMBER(10,2) DEFAULT 0,
    discount NUMBER(10,2) DEFAULT 0,
    estimated_completion TIMESTAMP,
    actual_completion TIMESTAMP,
    observations CLOB,
    technician_name VARCHAR2(100),
    current_kilometers NUMBER(10,2),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_orders_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_service_orders_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Tabela de Itens da Ordem de Serviço
CREATE TABLE service_order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id NUMBER NOT NULL,
    description VARCHAR2(500) NOT NULL,
    item_type VARCHAR2(20) NOT NULL,
    quantity NUMBER DEFAULT 1,
    unit_price NUMBER(10,2) DEFAULT 0,
    total_price NUMBER(10,2) DEFAULT 0,
    product_code VARCHAR2(100),
    requires_stock NUMBER(1) DEFAULT 0,
    stock_reserved NUMBER(1) DEFAULT 0,
    stock_product_id NUMBER,
    applied NUMBER(1) DEFAULT 0,
    observations CLOB,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_order_items_so FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE
);

-- Índices para performance
CREATE INDEX idx_service_orders_status ON service_orders(status);
CREATE INDEX idx_service_orders_client ON service_orders(client_id);
CREATE INDEX idx_service_orders_vehicle ON service_orders(vehicle_id);
CREATE INDEX idx_service_orders_created ON service_orders(createdAt);
CREATE INDEX idx_service_orders_technician ON service_orders(technician_name);
CREATE INDEX idx_service_orders_estimated ON service_orders(estimated_completion);

CREATE INDEX idx_service_order_items_so ON service_order_items(service_order_id);
CREATE INDEX idx_service_order_items_type ON service_order_items(item_type);
CREATE INDEX idx_service_order_items_product ON service_order_items(product_code);
CREATE INDEX idx_service_order_items_requires_stock ON service_order_items(requires_stock);
CREATE INDEX idx_service_order_items_applied ON service_order_items(applied);
