DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS inventory_movements;
DROP TABLE IF EXISTS inventory_items;
DROP TABLE IF EXISTS service_items;
DROP TABLE IF EXISTS service_orders;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS organizations;

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(50),
    description TEXT,
    active BOOLEAN,
    contact_email VARCHAR(100),
    contact_phone VARCHAR(20),
    address VARCHAR(200),
    document VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    birth_date TIMESTAMP,
    document VARCHAR(255),
    observations VARCHAR(255),
    phone VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_clients_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    client_id BIGINT,
    license_plate VARCHAR(20),
    brand VARCHAR(100),
    model VARCHAR(100),
    manufacture_date TIMESTAMP,
    color VARCHAR(50),
    observations VARCHAR(255),
    kilometers INTEGER,
    chassis_id VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_vehicles_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_vehicles_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    manufacturer VARCHAR(150),
    description TEXT,
    unit_cost NUMERIC(10,2),
    unit_price NUMERIC(10,2),
    active BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_parts_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE service_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    order_number VARCHAR(50) NOT NULL,
    vehicle_id BIGINT,
    client_id BIGINT,
    description TEXT,
    problem_description TEXT,
    diagnosis TEXT,
    solution_description TEXT,
    status VARCHAR(20),
    labor_cost NUMERIC(10,2),
    parts_cost NUMERIC(10,2),
    total_cost NUMERIC(10,2),
    discount NUMERIC(10,2),
    estimated_completion TIMESTAMP,
    actual_completion TIMESTAMP,
    observations TEXT,
    technician_name VARCHAR(100),
    current_kilometers NUMERIC(10,2),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_orders_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_service_orders_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_service_orders_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE service_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id BIGINT NOT NULL,
    description VARCHAR(500) NOT NULL,
    part_id BIGINT,
    item_type VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    total_price NUMERIC(10,2),
    product_code VARCHAR(100),
    stock_product_id BIGINT,
    requires_stock BOOLEAN,
    stock_reserved BOOLEAN,
    observations TEXT,
    applied BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_items_order FOREIGN KEY (service_order_id) REFERENCES service_orders(id),
    CONSTRAINT fk_service_items_part FOREIGN KEY (part_id) REFERENCES parts(id)
);

CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    part_id BIGINT NOT NULL,
    location VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    minimum_quantity INTEGER NOT NULL,
    unit_cost NUMERIC(10,2),
    sale_price NUMERIC(10,2),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_inventory_items_part FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT fk_inventory_items_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    inventory_item_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    service_order_id BIGINT,
    vehicle_id BIGINT,
    movement_type VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    reference_code VARCHAR(100),
    notes TEXT,
    movement_date TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_movements_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT fk_movements_part FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT fk_movements_service_order FOREIGN KEY (service_order_id) REFERENCES service_orders(id),
    CONSTRAINT fk_movements_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_movements_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    mfa_enabled BOOLEAN NOT NULL,
    mfa_secret VARCHAR(512),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_encrypted VARCHAR(512) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT,
    operation VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    module_name VARCHAR(255) NOT NULL,
    user_role VARCHAR(64) NOT NULL,
    entity_id BIGINT,
    occurred_at TIMESTAMP NOT NULL,
    event_hash VARCHAR(128) NOT NULL,
    blockchain_reference VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_events_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

INSERT INTO organizations (id, name, slug, active) VALUES (1, 'Default Org', 'default-org', true);
INSERT INTO users (id, organization_id, name, email, password, role, mfa_enabled)
VALUES (1, 1, 'Test Admin', 'admin@example.com', '{noop}password', 'ADMIN', false);
